'use strict';

/**
 * Formats captured HTTP traffic for Claude analysis.
 * Modes: 'api-docs' | 'auth' | 'summary' | 'full'
 */
function buildClaudeExport(captures, mode = 'api-docs') {
  switch (mode) {
    case 'api-docs': return buildApiDocs(captures);
    case 'auth':     return buildAuthExport(captures);
    case 'summary':  return buildSummary(captures);
    case 'full':     return buildFull(captures);
    default:         return buildApiDocs(captures);
  }
}

// ── API Documentation mode ────────────────────────────────────────────────────
function buildApiDocs(captures) {
  const endpoints = groupByEndpoint(captures);
  const lines = [
    '# API Traffic Analysis',
    `> Captured ${captures.length} requests across ${new Set(captures.map(c => c.host)).size} hosts`,
    '',
  ];

  for (const [host, methods] of Object.entries(endpoints)) {
    lines.push(`## Host: ${host}`, '');
    for (const [key, samples] of Object.entries(methods)) {
      const [method, path] = key.split(' ', 2);
      const sample = samples[0];
      const statuses = [...new Set(samples.map(s => s.responseStatus))];
      const ct = sample.contentType?.split(';')[0] || '';

      lines.push(`### ${method} ${path}`, '');
      lines.push(`- **Calls captured:** ${samples.length}`);
      lines.push(`- **Status codes:** ${statuses.join(', ')}`);
      lines.push(`- **Content-Type:** ${ct || '(none)'}`);
      lines.push(`- **Avg duration:** ${Math.round(samples.reduce((a,s) => a + (s.duration||0), 0) / samples.length)}ms`);

      // Notable request headers
      const notable = getNotableHeaders(sample.requestHeaders || {});
      if (notable.length) {
        lines.push('');
        lines.push('**Request Headers (notable):**');
        notable.forEach(([k, v]) => lines.push(`- \`${k}: ${truncate(v, 120)}\``));
      }

      // Request body sample
      if (sample.requestBody) {
        lines.push('');
        lines.push('**Request Body (sample):**');
        lines.push('```');
        lines.push(formatBody(sample.requestBody, 600));
        lines.push('```');
      }

      // Response body sample
      if (sample.responseBody) {
        lines.push('');
        lines.push('**Response Body (sample):**');
        lines.push('```');
        lines.push(formatBody(sample.responseBody, 800));
        lines.push('```');
      }

      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by Claude Intercept — ${new Date().toISOString()}*`);

  return lines.join('\n');
}

// ── Auth Extraction mode ─────────────────────────────────────────────────────
function buildAuthExport(captures) {
  const lines = [
    '# Auth & Credentials Extraction',
    `> Scanned ${captures.length} captures`,
    '',
    '## Authorization Headers',
    '',
  ];

  const authMap = new Map(); // token → { host, scheme, first_seen }
  const cookieMap = new Map(); // host → Set of cookie strings
  const apiKeyHeaders = ['x-api-key', 'x-auth-token', 'x-access-token', 'x-session-token',
                          'api-key', 'apikey', 'x-client-id', 'x-app-key'];

  for (const c of captures) {
    const h = c.requestHeaders || {};
    const host = c.host;

    // Authorization header
    const auth = h['authorization'] || h['Authorization'] || '';
    if (auth) {
      const [scheme, token] = auth.split(' ', 2);
      const key = `${scheme}::${token?.slice(-12)}`;
      if (!authMap.has(key)) {
        authMap.set(key, { host, scheme, token: token || '', url: c.url });
      }
    }

    // API key headers
    for (const hName of apiKeyHeaders) {
      const val = h[hName] || h[hName.toLowerCase()] || '';
      if (val) {
        const key = `${hName}::${val.slice(-8)}`;
        if (!authMap.has(key)) {
          authMap.set(key, { host, scheme: hName, token: val, url: c.url });
        }
      }
    }

    // Cookies
    const cookie = h['cookie'] || h['Cookie'] || '';
    if (cookie) {
      if (!cookieMap.has(host)) cookieMap.set(host, new Set());
      cookieMap.get(host).add(cookie);
    }

    // Bearer in request body / query string
    const urlObj = tryParseUrl(c.url);
    if (urlObj) {
      for (const [k, v] of urlObj.searchParams.entries()) {
        if (/token|access_token|api_key|bearer/i.test(k)) {
          const key = `query::${k}::${v.slice(-8)}`;
          if (!authMap.has(key)) {
            authMap.set(key, { host, scheme: `query param: ${k}`, token: v, url: c.url });
          }
        }
      }
    }
  }

  if (authMap.size === 0) {
    lines.push('*No Authorization headers found.*', '');
  } else {
    for (const [, info] of authMap) {
      lines.push(`### ${info.scheme}`);
      lines.push(`- **Host:** \`${info.host}\``);
      lines.push(`- **From:** \`${info.url}\``);
      lines.push(`- **Value:** \`${info.token}\``);
      lines.push('');
    }
  }

  lines.push('## Cookies', '');
  if (cookieMap.size === 0) {
    lines.push('*No cookies found.*', '');
  } else {
    for (const [host, cookies] of cookieMap) {
      lines.push(`### ${host}`);
      for (const cookie of cookies) {
        const pairs = cookie.split(';').map(s => s.trim()).filter(Boolean);
        pairs.forEach(p => lines.push(`- \`${truncate(p, 200)}\``));
      }
      lines.push('');
    }
  }

  // JSON body token extraction
  lines.push('## Tokens in Request/Response Bodies', '');
  const bodyTokens = [];
  const tokenKeys = /token|access_token|refresh_token|id_token|session_id|sessionToken|auth/i;
  for (const c of captures) {
    for (const body of [c.requestBody, c.responseBody]) {
      if (!body) continue;
      try {
        const parsed = JSON.parse(body);
        findKeys(parsed, tokenKeys, c.host, c.url, bodyTokens);
      } catch {}
    }
  }
  if (!bodyTokens.length) {
    lines.push('*No tokens found in JSON bodies.*', '');
  } else {
    for (const bt of bodyTokens.slice(0, 30)) {
      lines.push(`- **\`${bt.key}\`** on \`${bt.host}\`: \`${truncate(bt.value, 120)}\``);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Claude Intercept — ${new Date().toISOString()}*`);
  return lines.join('\n');
}

// ── Summary mode ──────────────────────────────────────────────────────────────
function buildSummary(captures) {
  const hosts = {};
  let totalDuration = 0;
  const methods = {};
  const statuses = {};

  for (const c of captures) {
    hosts[c.host] = (hosts[c.host] || 0) + 1;
    methods[c.method] = (methods[c.method] || 0) + 1;
    const sc = String(Math.floor((c.responseStatus || 0) / 100) * 100);
    statuses[sc] = (statuses[sc] || 0) + 1;
    totalDuration += c.duration || 0;
  }

  const lines = [
    '# Traffic Summary',
    '',
    `**Total requests:** ${captures.length}`,
    `**Unique hosts:** ${Object.keys(hosts).length}`,
    `**Avg response time:** ${Math.round(totalDuration / captures.length)}ms`,
    '',
    '## Requests by Host',
    '',
    ...Object.entries(hosts)
      .sort((a, b) => b[1] - a[1])
      .map(([h, n]) => `- \`${h}\` — ${n} requests`),
    '',
    '## HTTP Methods',
    '',
    ...Object.entries(methods).map(([m, n]) => `- **${m}:** ${n}`),
    '',
    '## Status Codes',
    '',
    ...Object.entries(statuses).map(([s, n]) => `- **${s}xx:** ${n}`),
    '',
    '## Recent Endpoints',
    '',
    ...captures.slice(0, 40).map(c =>
      `- \`${c.method} ${c.url}\` → ${c.responseStatus || '?'} (${c.duration || 0}ms)`
    ),
    '',
    '---',
    `*Generated by Claude Intercept — ${new Date().toISOString()}*`,
  ];

  return lines.join('\n');
}

// ── Full detail mode ─────────────────────────────────────────────────────────
function buildFull(captures) {
  const lines = [
    '# Full Capture Detail',
    `> ${captures.length} requests`,
    '',
  ];

  for (const c of captures) {
    lines.push(`## [${c.id}] ${c.method} ${c.url}`);
    lines.push(`**Status:** ${c.responseStatus}  **Duration:** ${c.duration}ms  **Time:** ${new Date(c.timestamp).toISOString()}`);
    lines.push('');
    lines.push('### Request Headers');
    for (const [k, v] of Object.entries(c.requestHeaders || {})) {
      lines.push(`- \`${k}: ${truncate(String(v), 200)}\``);
    }
    if (c.requestBody) {
      lines.push('### Request Body');
      lines.push('```');
      lines.push(formatBody(c.requestBody, 1200));
      lines.push('```');
    }
    lines.push('### Response Headers');
    for (const [k, v] of Object.entries(c.responseHeaders || {})) {
      lines.push(`- \`${k}: ${truncate(String(v), 200)}\``);
    }
    if (c.responseBody) {
      lines.push('### Response Body');
      lines.push('```');
      lines.push(formatBody(c.responseBody, 2000));
      lines.push('```');
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push(`*Generated by Claude Intercept — ${new Date().toISOString()}*`);
  return lines.join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function groupByEndpoint(captures) {
  const result = {};
  for (const c of captures) {
    const host = c.host;
    if (!result[host]) result[host] = {};
    const normalizedPath = normalizePath(c.path || '/');
    const key = `${c.method} ${normalizedPath}`;
    if (!result[host][key]) result[host][key] = [];
    result[host][key].push(c);
  }
  return result;
}

function normalizePath(path) {
  // Replace UUIDs, numeric IDs, hex strings with placeholders
  return path
    .replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi, ':uuid')
    .replace(/\/\d+(?=\/|$|\?)/g, '/:id')
    .replace(/[?#].*$/, ''); // strip query string for grouping
}

function getNotableHeaders(headers) {
  const notableKeys = [
    'authorization', 'cookie', 'x-api-key', 'x-auth-token', 'x-access-token',
    'content-type', 'accept', 'origin', 'referer', 'x-requested-with',
    'x-forwarded-for', 'user-agent',
  ];
  return Object.entries(headers).filter(([k]) => notableKeys.includes(k.toLowerCase()));
}

function formatBody(body, maxLen) {
  if (!body) return '';
  let out = body;
  try { out = JSON.stringify(JSON.parse(body), null, 2); } catch {}
  return truncate(out, maxLen);
}

function truncate(str, max) {
  if (!str) return '';
  const s = String(str);
  return s.length > max ? s.slice(0, max) + `… [+${s.length - max} chars]` : s;
}

function tryParseUrl(url) {
  try { return new URL(url); } catch { return null; }
}

function findKeys(obj, pattern, host, url, results, prefix = '') {
  if (typeof obj !== 'object' || obj === null || results.length > 30) return;
  for (const [k, v] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${k}` : k;
    if (pattern.test(k) && typeof v === 'string' && v.length > 8) {
      results.push({ key: fullKey, value: v, host, url });
    }
    if (typeof v === 'object') findKeys(v, pattern, host, url, results, fullKey);
  }
}

module.exports = { buildClaudeExport };
